[package]
name = "plotters-iced-demo"
version = "0.1.0"
edition = "2018"

[dependencies]
plotters = "0.3.0"
plotters-bitmap = "0.3.0"
iced = { version="0.3.0", features=["image"] }
[dev-dependencies]
minifb = "0.19.3"
